name: Fetch City/Region News (hourly)

on:
  schedule:
    - cron: '0 * * * *'   # каждый час
  workflow_dispatch:      # запуск вручную
  push:
    paths:
      - .github/workflows/fetch-city-news.yml
      - scripts/fetch_news.py

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fetch Google News and build JSON
        run: |
          python scripts/fetch_news.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/news.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(news): update news.json"
            git push
          fi
